#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
filter=""
dry="0"

echo "script_dir=$script_dir"

cd $script_dir
scripts=$(find runs -maxdepth 1 -mindepth 1 -executable -type f)

while [[ $# > 0 ]]; do
  if [[ "$1" == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute: $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "run: filter=$filter"
log "run: updating the system"
execute sudo pacman -Syu --noconfirm
execute yay -Syu --noconfirm

for script in $scripts; do
  if echo "$script" | grep -qv "$filter"; then
    log "filtered: $filter -- $script"
    continue
  fi
  log "running script: $script"
  execute ./$script
done
