#!/usr/bin/env bash

echo "installing wireguard-tools..."

sudo pacman -S --noconfirm --needed wireguard-tools
sudo pacman -S --noconfirm --needed systemd-resolvconf

# to use wireguard, create wireguard config in e.g. $HOME/wireguard/wg0.conf
# then use:
#  - sudo wg-quick up /home/mc2/wireguard/wg0.conf
#  - sudo wg-quick down /home/mc2/wireguard/wg0.conf
